### ISSUE TITLE
Allow all formats supported by PIL

### ISSUE THREAD

**Issue by wearpants** [azaghal/pydenticon#5]
It'd be handy to be able to generate an image in any of the formats supported by PIL. It looks as if that'd be as simple as renaming `_generate_png` to `_generate_bytes` or such, and passing the `output_format` argument through to PIL here: https://github.com/azaghal/pydenticon/blob/master/pydenticon/__init__.py#L247

**Comment by azaghal** [comment]
That would probably  be quite a simple addition. As a curiosity, did you have a need on using generated identicons with some specific format?

Sorry for being unresponsive, been a bit busy, and this issue apparently slipped by me :)

**Comment by wearpants** [comment]
I was using this in Django with `factory` to generate data for user profiles in tests... don't recall the exact reason why I wanted something else out of PIL. Thanks for fixing!

**Comment by azaghal** [comment]
Implemented and pushed to master branch. However, transparency is currently handled properly only for the `PNG` format.
